title: Animal Play
subtitle: 'For violin, clarinet, cello, piano, and synthesizer'
composer: Jonathan Marmor
sections:
    -
        num_bars_options: [8, 4]
        num_bars_weights: []
        sections:
            -
                soloist: violin
                accompanists:
                    -
                        instrument: clarinet
                    -
                        instrument: cello
                section_setting_1: 'example'
                section_setting_2: 'hello'
                sections:
                    -
                        harmony_type: drone
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                    -
                        harmony_type: free
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
            -
                soloist: violin
                accompanists:
                    -
                        instrument: clarinet
                    -
                        instrument: cello
                section_setting_1:
                section_setting_2:
                sections:
                    -
                        harmony_type: drone
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                    -
                        harmony_type: free
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
    -
        num_bars_options: [8, 4, 2, 16]
        num_bars_weights: []
        sections:
            -
                soloist: clarinet
                accompanists:
                    -
                        instrument: violin
                        style: doublestops
                        register: highish
                    -
                        instrument: cello
                        style: doublestops
                        register: lowish
                section_setting_1:
                section_setting_2:
                sections:
                    -
                        harmony_type: drone
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                    -
                        harmony_type: free
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
            -
                soloist: cello
                accompanists:
                    -
                        instrument: clarinet
                        register: highish
                    -
                        instrument: violin
                        style: doublestops
                        register: highish
                section_setting_1:
                section_setting_2:
                sections:
                    -
                        harmony_type: drone
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                    -
                        harmony_type: free
                        sections:
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
                            -
                                dynamic: quiet
                            -
                                dynamic: loud
